server {
    listen 80;
    server_name _;

    client_max_body_size 50m;

    location /static/ {
        proxy_pass http://app:8000/static/;
    }

    location /hls/ {
        proxy_pass http://mediamtx:8888/;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin * always;
    }

    location ~ ^/[A-Za-z0-9_.-]+/.+\.(m3u8|m4s|mp4|ts)$ {
        proxy_pass http://mediamtx:8888$request_uri;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin * always;
    }

    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
