logLevel: info
logDestinations: [stdout]
api: true
apiAddress: :9997
metrics: true
metricsAddress: :9998
rtsp: true
rtspAddress: :8554
rtspTransports: [tcp]
rtmp: true
rtmpAddress: :1935
hls: true
hlsAddress: :8888
hlsAllowOrigins: ['*']
hlsAlwaysRemux: false
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
webrtc: false
srt: false
paths:
  all:
    source: publisher
