logLevel: info
logDestinations: [stdout]
authMethod: internal
authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
      - action: read
      - action: playback
  - user: any
    pass:
    ips: ['127.0.0.1', '::1', '10.0.0.0/8', '172.16.0.0/12']
    permissions:
      - action: api
      - action: metrics
api: true
apiAddress: :9997
metrics: true
metricsAddress: :9998
rtsp: true
rtspAddress: :8554
rtspTransports: [udp, tcp]
rtmp: true
rtmpAddress: :1935
hls: true
hlsAddress: :8888
hlsAllowOrigins: ['*']
hlsAlwaysRemux: false
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
webrtc: false
srt: false
paths:
  all:
    source: publisher
